INSERT INTO EMPLOYEE VALUES (1, 'IVAN', 'IVANOU', 1, 'MANAGER', 'MALE', TO_DATE('1-5-1981', 'DD-MM-YYYY'));
INSERT INTO EMPLOYEE VALUES (2, 'DZMITRY', 'PIATROU', 1, 'SALES', 'MALE', TO_DATE('1-12-1987', 'DD-MM-YYYY'));
INSERT INTO EMPLOYEE VALUES (3, 'SARA', 'CONOR', 2, 'MANAGER', 'FEMALE', TO_DATE('10-5-1999', 'DD-MM-YYYY'));
INSERT INTO EMPLOYEE VALUES (4, 'RAMAN', 'SIDARAU', 2, 'CLERK', 'MALE', TO_DATE('2-5-1985', 'DD-MM-YYYY'));
INSERT INTO EMPLOYEE VALUES (5, 'PIOTR', 'VOLODIN', 1, 'CLERK', 'MALE', TO_DATE('4-5-1998', 'DD-MM-YYYY'));

COMMIT;